const ActionName = {

    LOGIN: "Account/SignIn",
    SIGNUP: "SIGNUP",
    USER:"USER",
    CREATE_W9:"CREATE_W9",
    CREATE_W8:"CREATE_W8",
    CREATE_W8_ECI:"CREATE_W8_ECI",
    individualAccountHolder: "individualAccountHolder",
    GetCountries: "GetCountries",
    GetCountriesCode: "GetCountriesCode",
    GetAllIncomeCodes :"GetAllIncomeCodes",
    GetStateByCountryId:"GetStateByCountryId",
    InsertAccountHolderDetail:"InsertAccountHolderDetail",
    CREATE_8233:"CREATE_8233",
    postSecurutyCode:"postSecurityCode",
    GetSecurityQuestions:"GetSecurityQuestions",
    GetTinTypes:"GetTinTypes",
    PostFormSelection:"PostFormSelection",
    getBreadCrums:"getBreadCrums",
    GetAgentPaymentType:"GetAgentPaymentType",
    //PDFs
    W9PDF:"W9PDF",
    //
    GetAgentCapacityHiddenForEform: "GetAgentCapacityHiddenForEform",
    GetAgentChapter4EntityTypeHiddenForEform: "GetAgentChapter4EntityTypeHiddenForEform",
    GetAgentChapter3EntityTypeHiddenForEform: "GetAgentChapter3EntityTypeHiddenForEform",
    GetAgentChapter4EntityTypeImportantForEform: "GetAgentChapter4EntityTypeImportantForEform",
    GetAgentDocumentationMandatoryForEform: "GetAgentDocumentationMandatoryForEform",
    GetAgentExemptionCodeDisabledForEform: "GetAgentExemptionCodeDisabledForEform",
    GetAgentIncomeCodeHiddenForEform: "GetAgentIncomeCodeHiddenForEform",
    GetAgentUSVisaTypeHiddenForEform: "GetAgentUSVisaTypeHiddenForEform",
    GetAgentFATCAExemptionCodeHiddenForEform: "GetAgentFATCAExemptionCodeHiddenForEform",
    GetAgentFATCAEntityGIINChallengeDisabledForEform: "GetAgentFATCAEntityGIINChallengeDisabledForEform",
    GetAgentSPTQuestionHiddenForEform: "GetAgentSPTQuestionHiddenForEform",
    GetAgentWrittenStatementSelectionByAgentIdForEform: "GetAgentWrittenStatementSelectionByAgentIdForEform",
    GetAgentTINTypeSelectionByIdForEform: "GetAgentTINTypeSelectionByIdForEform",
    GetAgentCountriesImportantForEform:"GetAgentCountriesImportantForEform",
    GetChapter3Status:"GetChapter3Status",
    GetChapter4Statuses:"GetChapter4Statuses",
    GetLimitationBenefits:"GetLimitationBenefits",
    GetIncomeTypes:"GetIncomeTypes",
    GetAgentIncomeTypeHiddenAllowAnoymo:"GetAgentIncomeTypeHiddenAllowAnoymo",
    SendOTPMail:"SendOTPMail",
    
    InsertW9IndividualEntityUSForm:"InsertW9IndividualEntityUSForm",
    InsertW8BENEEntityNonUSForm:"InsertW8BENEEntityNonUSForm",
    InsertW8BENIndividualNonUS:"InsertW8BENIndividualNonUS",
    InsertW8ECIIndividualEntityNonUSForm:"InsertW8ECIIndividualEntityNonUSForm",
    InsertW8EXPFormEntityNonUs:"InsertW8EXPFormEntityNonUs",
    InsertW8IMYEntityNonForm:"InsertW8IMYEntityNonForm",
    InsertForm8233IndividualNonUSForm:"InsertForm8233IndividualNonUSForm",

    GetByW9IndividualEntityUSFormId:"GetByW9IndividualEntityUSFormId",
    
  };

  export default ActionName;